# Generated by Django 3.2.7 on 2021-09-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.IntegerField(auto_created=True, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_orden', models.DateTimeField()),
                ('estado', models.CharField(choices=[('SOL', 'Solicitada'), ('APR', 'Aprobada'), ('NUL', 'Anulada')], default='SOL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15)),
                ('Nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Correo', models.EmailField(max_length=254)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenando', to='ESWAPP.orden')),
            ],
        ),
    ]
