# Generated by Django 3.1.6 on 2021-09-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESWAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='alto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='ancho',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
