# Generated by Django 3.1.6 on 2021-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESWAPP', '0002_auto_20210907_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='Cristal',
            field=models.CharField(choices=[('CRD', 'Crudo'), ('LMD', 'Laminado'), ('ESM', 'Esmerilado')], default='CRD', max_length=100),
        ),
    ]
