version: "3"

services:
  mysql:
    image: mysql
    volumes:
        - ./database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "db"